<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from ca.sdda.dogregistry/xml/schema/CRM/Dogregistry/DogTitles.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:d98ee75bf338ae59faae851935fff53b)
 */
use CRM_Dogregistry_ExtensionUtil as E;

/**
 * Database access object for the DogTitles entity.
 */
class CRM_Dogregistry_DAO_DogTitles extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_dog_titles';

  /**
   * Primary key field(s).
   *
   * @var string[]
   */
  public static $_primaryKey = ['dogId'];

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique DogTitles ID
   *
   * @var int|string|null
   *   (SQL type: int)
   *   Note that values will be retrieved from the database as a string.
   */
  public $dogId;

  /**
   * Title Name
   *
   * @var string|null
   *   (SQL type: varchar(50))
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * Determine if a special title
   *
   * @var string|null
   *   (SQL type: varchar(2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $Honours;

  /**
   * Score
   *
   * @var string|null
   *   (SQL type: INT)
   *   Note that values will be retrieved from the database as a string.
   */
  public $titleScore;

  /**
   * Title DATE
   *
   * @var string|null
   *   (SQL type: DATE)
   *   Note that values will be retrieved from the database as a string.
   */
  public $titleDate;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_dog_titles';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Dog Titleses') : E::ts('Dog Titles');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'dogId', 'civicrm_registered_dogs', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'dogId' => [
          'name' => 'dogId',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Dogid'),
          'description' => E::ts('Unique DogTitles ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_dog_titles.dogId',
          'table_name' => 'civicrm_dog_titles',
          'entity' => 'DogTitles',
          'bao' => 'CRM_Dogregistry_DAO_DogTitles',
          'localizable' => 0,
          'FKClassName' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Description'),
          'description' => E::ts('Title Name'),
          'maxlength' => 50,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_dog_titles.description',
          'table_name' => 'civicrm_dog_titles',
          'entity' => 'DogTitles',
          'bao' => 'CRM_Dogregistry_DAO_DogTitles',
          'localizable' => 0,
          'add' => NULL,
        ],
        'Honours' => [
          'name' => 'Honours',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Honours'),
          'description' => E::ts('Determine if a special title'),
          'maxlength' => 2,
          'size' => CRM_Utils_Type::TWO,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_dog_titles.Honours',
          'table_name' => 'civicrm_dog_titles',
          'entity' => 'DogTitles',
          'bao' => 'CRM_Dogregistry_DAO_DogTitles',
          'localizable' => 0,
          'add' => NULL,
        ],
        'titleScore' => [
          'name' => 'titleScore',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Titlescore'),
          'description' => E::ts('Score'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_dog_titles.titleScore',
          'table_name' => 'civicrm_dog_titles',
          'entity' => 'DogTitles',
          'bao' => 'CRM_Dogregistry_DAO_DogTitles',
          'localizable' => 0,
          'add' => NULL,
        ],
        'titleDate' => [
          'name' => 'titleDate',
          'type' => CRM_Utils_Type::T_DATE,
          'title' => E::ts('Titledate'),
          'description' => E::ts('Title DATE'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_dog_titles.titleDate',
          'table_name' => 'civicrm_dog_titles',
          'entity' => 'DogTitles',
          'bao' => 'CRM_Dogregistry_DAO_DogTitles',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'dog_titles', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'dog_titles', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
