<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2018
 *
 * Generated from /var/www/wp-content/uploads/civicrm/ext/ca.sdda.dogregistry/xml/schema/CRM/Dogregistry/RegisteredDogs.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:3516b4342a1b989bbe9cfa0b5fa38311)
 */

/**
 * Database access object for the RegisteredDogs entity.
 */
class CRM_Dogregistry_DAO_RegisteredDogs extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_registered_dogs';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  static $_log = TRUE;

  /**
   * Unique RegisteredDogs ID
   *
   * @var int unsigned
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int unsigned
   */
  public $contact_id;

  /**
   * Registered dog Name
   *
   * @var string
   */
  public $registered_name;

  /**
   * Dogs Call Name
   *
   * @var string
   */
  public $call_name;

  /**
   * Name for certs
   *
   * @var string
   */
  public $preferred_name;

  /**
   * Dog gender
   *
   * @var string
   */
  public $sex;

  /**
   * Spayed or Neutered
   *
   * @var string
   */
  public $altered;

  /**
   * Date of birth
   *
   * @var string
   */
  public $date_of_birth;

  /**
   * Active date
   *
   * @var string
   */
  public $active_date;

  /**
   * Inactive Date
   *
   * @var string
   */
  public $inactive_date;

  /**
   * Dog breed
   *
   * @var string
   */
  public $breed_name;

  /**
   * Scent titles
   *
   * @var string
   */
  public $other_titles;

  /**
   * Other titles
   *
   * @var string
   */
  public $other_title_description;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_registered_dogs';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique RegisteredDogs ID',
          'required' => TRUE,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Contact',
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'registered_name' => [
          'name' => 'registered_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Registered Name'),
          'description' => 'Registered dog Name',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'call_name' => [
          'name' => 'call_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Call Name'),
          'description' => 'Dogs Call Name',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'preferred_name' => [
          'name' => 'preferred_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Preferred Name'),
          'description' => 'Name for certs',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'sex' => [
          'name' => 'sex',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Sex'),
          'description' => 'Dog gender',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'altered' => [
          'name' => 'altered',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Altered'),
          'description' => 'Spayed or Neutered',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'date_of_birth' => [
          'name' => 'date_of_birth',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Date Of Birth'),
          'description' => 'Date of birth',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'active_date' => [
          'name' => 'active_date',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Active Date'),
          'description' => 'Active date',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'inactive_date' => [
          'name' => 'inactive_date',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Inactive Date'),
          'description' => 'Inactive Date',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'breed_name' => [
          'name' => 'breed_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Breed Name'),
          'description' => 'Dog breed',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'other_titles' => [
          'name' => 'other_titles',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Other Titles'),
          'description' => 'Scent titles',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
        'other_title_description' => [
          'name' => 'other_title_description',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Other Title Description'),
          'description' => 'Other titles',
          'size' => CRM_Utils_Type::TWO,
          'table_name' => 'civicrm_registered_dogs',
          'entity' => 'RegisteredDogs',
          'bao' => 'CRM_Dogregistry_DAO_RegisteredDogs',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'registered_dogs', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'registered_dogs', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
