-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_registered_dogs`;
DROP TABLE IF EXISTS `civicrm_dog_breed`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_dog_breed
-- *
-- * List of available breeds for registration
-- *
-- *******************************************************/
CREATE TABLE `civicrm_dog_breed` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique DogBreed ID',
  `Breed` text COMMENT 'Dog Breed',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_registered_dogs
-- *
-- * Registered Dogs
-- *
-- *******************************************************/
CREATE TABLE `civicrm_registered_dogs` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique RegisteredDogs ID',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `registered_name` varchar(0) COMMENT 'Registered dog Name',
  `call_name` varchar(0) COMMENT 'Dogs Call Name',
  `preferred_name` varchar(0) COMMENT 'Name for certs',
  `sex` varchar(0) COMMENT 'Dog gender',
  `altered` varchar(0) COMMENT 'Spayed or Neutered',
  `date_of_birth` varchar(0) COMMENT 'Date of birth',
  `active_date` varchar(0) COMMENT 'Active date',
  `inactive_date` varchar(0) COMMENT 'Inactive Date',
  `breed_name` varchar(0) COMMENT 'Dog breed',
  `other_titles` varchar(0) COMMENT 'Scent titles',
  `other_title_description` varchar(0) COMMENT 'Other titles',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_registered_dogs_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
